//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Librarius_DL.Models.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class BookCopies
    {
        public int CopyID { get; set; }
        public Nullable<int> BookID { get; set; }
        public byte[] QRCode { get; set; }
        public Nullable<int> StatusID { get; set; }
        public Nullable<int> ConditionID { get; set; }
    
        public virtual Books Books { get; set; }
        public virtual Conditions Conditions { get; set; }
        public virtual Statuses Statuses { get; set; }
    }
}
