//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Librarius_DL.Models.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Conditions
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Conditions()
        {
            this.BookCopies = new HashSet<BookCopies>();
        }
    
        public int ConditionID { get; set; }
        public string ConditionName { get; set; }
        public string ConditionDescription { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BookCopies> BookCopies { get; set; }
    }
}
