//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Librarius_DL.Models.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Fines
    {
        public int FineID { get; set; }
        public Nullable<int> TransactionID { get; set; }
        public decimal Amount { get; set; }
        public Nullable<System.DateTime> PaidDate { get; set; }
        public int FineStatusID { get; set; }
    
        public virtual Transactions Transactions { get; set; }
        public virtual FineStatuses FineStatuses { get; set; }
    }
}
